"""
OAI Text-to-Image 节点
支持千问文生图和Wan2.2文生图
"""
from .oaigc import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

print("033[32m[OAI Text-to-Image] 节点加载成功！033[0m")
print("  - OAI-千问文生图 (千问文生图)")
print("  - OAI-即梦绘画 (即梦绘画)")
print("  - OAI-万物溶图 (AI万物溶图)")
print("  - OAI-AI证件照 (AI证件照)")
print("  - OAI-人物场景融合 (人物场景融合)")
print("  - OAI-人物姿态迁移 (人物姿态迁移)")
print("  - OAI-千姿百态 (千姿百态)")
print("  - OAI-Qwen编辑图像 (Qwen编辑图像)")
print("  - OAI-AI反推出图 (AI反推出图)")
print("  - OAI-线稿成图 (线稿成图)")
print("  - OAI-AI废片拯救 (AI废片拯救)")
print("  - OAI-真人一键手办 (真人一键手办)")
print("  - OAI-智能消除 (智能消除)")
print("  - OAI-老照片修复 (老照片修复)")
print("  - OAI-电商带货 (电商带货)")
print("  - OAI-Flux图像编辑 (Flux图像编辑)")
print("  - OAI-可灵绘图 (可灵绘图)")
print("  - OAI-吉卜力风格 (吉卜力风格)")
print("  - OAI-产品重打光 (产品重打光)")
print("  - OAI-高清放大 (高清放大)")
print("  - OAI-毛坯房装修 (毛坯房装修)")
print("  - OAI-万物迁移 (万物迁移)")
print("  - OAI-AI扩图 (AI扩图)")
print("  - OAI-AI抠图 (AI抠图)")
print("  - OAI-新年剪纸风 (新年剪纸风)")
print("  - OAI-AI线稿上色 (AI线稿上色)")
print("  - OAI-一键换衣 (一键换衣)")
print("  - OAI-文生视频 (文生视频)")
print("  - OAI-Sora2视频 (Sora2视频)")
print("  - OAI-视频动作迁移 (视频动作迁移)")
print("  - OAI-视频对口型 (视频对口型)")
print("  - OAI-AI图片数字人 (AI图片数字人)")
print("  - OAI-AI视频替换人物 (AI视频替换人物)")
print("  - OAI-首尾帧 (首尾帧)")
print("  - OAI-图生视频 (图生视频)")
print("  - OAI-音频驱动图片 (音频驱动图片)")
print("  - OAI-多参视频 (多参视频)")
print("  - OAI-即梦视频3.0 (即梦视频3.0)")
print("  - OAI-doubao4.0 (豆包绘图4.0)")
print("  - OAI-万物换背景 (万物换背景)")
print("  - OAI-Wan2.2文生图 (Wan2.2文生图)")
